kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-cluster-rolebinding
subjects:
- kind: User
  name: system:serviceaccount:default:acceso-api
  apiGroup: rbac.authorization.k8s.io
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-role