apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-role
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["pods"]
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["services"]
- apiGroups: ["apps"]
  verbs: ["get", "list"]
  resources: ["deployments","replicasets"]