apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: products
    department: sales
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50001 # puertos que usan los pods
    name: http-50001
    # nodePort: 31446
  # - protocol: TCP
  #   port: 443
  #   targetPort: 8443 # puertos que usan los pods
  #   name: https-8443

# kubectl exec -it pod-name -- sh
# apk add --no-cache curl
# curl cluster-ip:<port>
# curl cluster-ip.<namespace>:<port>
# curl cluster-ip.<namespace>.svc.cluster.local:<port>
# -> cluster-ip es el valor de clusterIP en tu servicio.