apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    # app: nodejs-label
    app: mysql-client
spec:
  containers:
   - name: mysql
     image: mysql:5.7
     env:
      - name: MYSQL_ROOT_PASSWORD
        value: mypassword
