apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
  namespace: default
  labels:
    app: metrics
spec:
  type: ClusterIP #NodePort, LoadBalancer, ExternalName, None (headless)
  selector:
    app: metrics
    # version: v1
  ports:
  - port: 80 # obligatorio
    #protocol: TCP
    targetPort: 8080 # puertos que usan los pods
    name: http-8080
    # name: http-appmetrics# <protocol>[-<suffix>].
    # appProtocol: http # <protocol>
    # nodePort: 32225 #<30000 - 3XYZAC>

# <service-name>.<namespace>.svc.cluster.local

# kubectl exec -it pod-name -- sh
# apk add --no-cache curl
# curl cluster-ip:80
# -> cluster-ip es el valor de clusterIP en tu servicio.


# kubectl expose deploy/my-deployment --name mysvc2 --port 8000 --target-port 8080
# kubectl create svc clusterip mysvc3 --tcp=9000:8080